server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:account-service}
    driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${DB_USERNAME:elias20}
        password: ${DB_PASSWORD:ItsEliastyles2}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

